module purge; module load devel/python/3.11.7-gnu-14.2

cd examples/kitepower_sys
mkdir -p sim_logs
set -euo pipefail
source "../../venv/bin/activate"


# for s in closed_loop_simulation_cluster_with_noise_added_in_z_config_2_1.py closed_loop_simulation_cluster_with_noise_added_in_z_config_2_2.py closed_loop_simulation_cluster_with_noise_added_in_z_config_2_3.py closed_loop_simulation_cluster_with_noise_added_in_z_config_2_4.py closed_loop_simulation_cluster_with_noise_added_in_z_config_2_5.py \
#           closed_loop_simulation_cluster_with_noise_added_in_z_config_2_6.py closed_loop_simulation_cluster_with_noise_added_in_z_config_2_7.py closed_loop_simulation_cluster_with_noise_added_in_z_config_2_8.py closed_loop_simulation_cluster_with_noise_added_in_z_config_2_9.py closed_loop_simulation_cluster_with_noise_added_in_z_config_2_10.py \
#           closed_loop_simulation_cluster_with_noise_added_in_z_config_2_11.py closed_loop_simulation_cluster_with_noise_added_in_z_config_2_12.py closed_loop_simulation_cluster_with_noise_added_in_z_config_2_13.py closed_loop_simulation_cluster_with_noise_added_in_z_config_2_14.py closed_loop_simulation_cluster_with_noise_added_in_z_config_2_15.py \
#           closed_loop_simulation_cluster_with_noise_added_in_z_config_2_16.py closed_loop_simulation_cluster_with_noise_added_in_z_config_2_17.py closed_loop_simulation_cluster_with_noise_added_in_z_config_2_18.py closed_loop_simulation_cluster_with_noise_added_in_z_config_2_19.py closed_loop_simulation_cluster_with_noise_added_in_z_config_2_20.py ;
# for s in closed_loop_simulation_cluster_with_noise_added_in_z_config_3_1.py closed_loop_simulation_cluster_with_noise_added_in_z_config_3_2.py closed_loop_simulation_cluster_with_noise_added_in_z_config_3_3.py closed_loop_simulation_cluster_with_noise_added_in_z_config_3_4.py closed_loop_simulation_cluster_with_noise_added_in_z_config_3_5.py \
#           closed_loop_simulation_cluster_with_noise_added_in_z_config_3_6.py closed_loop_simulation_cluster_with_noise_added_in_z_config_3_7.py closed_loop_simulation_cluster_with_noise_added_in_z_config_3_8.py closed_loop_simulation_cluster_with_noise_added_in_z_config_3_9.py closed_loop_simulation_cluster_with_noise_added_in_z_config_3_10.py \
#           closed_loop_simulation_cluster_with_noise_added_in_z_config_3_11.py closed_loop_simulation_cluster_with_noise_added_in_z_config_3_12.py closed_loop_simulation_cluster_with_noise_added_in_z_config_3_13.py closed_loop_simulation_cluster_with_noise_added_in_z_config_3_14.py closed_loop_simulation_cluster_with_noise_added_in_z_config_3_15.py \
#           closed_loop_simulation_cluster_with_noise_added_in_z_config_3_16.py closed_loop_simulation_cluster_with_noise_added_in_z_config_3_17.py closed_loop_simulation_cluster_with_noise_added_in_z_config_3_18.py closed_loop_simulation_cluster_with_noise_added_in_z_config_3_19.py closed_loop_simulation_cluster_with_noise_added_in_z_config_3_20.py ;
for s in closed_loop_simulation_cluster_with_noise_added_in_z_config_1_1_with_disturbance_2.py closed_loop_simulation_cluster_with_noise_added_in_z_config_1_2_with_disturbance_2.py closed_loop_simulation_cluster_with_noise_added_in_z_config_1_3_with_disturbance_2.py closed_loop_simulation_cluster_with_noise_added_in_z_config_1_4_with_disturbance_2.py closed_loop_simulation_cluster_with_noise_added_in_z_config_1_5_with_disturbance_2.py \
          closed_loop_simulation_cluster_with_noise_added_in_z_config_1_6_with_disturbance_2.py closed_loop_simulation_cluster_with_noise_added_in_z_config_1_7_with_disturbance_2.py closed_loop_simulation_cluster_with_noise_added_in_z_config_1_8_with_disturbance_2.py closed_loop_simulation_cluster_with_noise_added_in_z_config_1_9_with_disturbance_2.py closed_loop_simulation_cluster_with_noise_added_in_z_config_1_10_with_disturbance_2.py ;
          # closed_loop_simulation_cluster_with_noise_added_in_z_config_1_11_with_disturbance.py closed_loop_simulation_cluster_with_noise_added_in_z_config_1_12_with_disturbance.py closed_loop_simulation_cluster_with_noise_added_in_z_config_1_13_with_disturbance.py closed_loop_simulation_cluster_with_noise_added_in_z_config_1_14_with_disturbance.py closed_loop_simulation_cluster_with_noise_added_in_z_config_1_15_with_disturbance.py \
          # closed_loop_simulation_cluster_with_noise_added_in_z_config_1_16_with_disturbance.py closed_loop_simulation_cluster_with_noise_added_in_z_config_1_17_with_disturbance.py closed_loop_simulation_cluster_with_noise_added_in_z_config_1_18_with_disturbance.py closed_loop_simulation_cluster_with_noise_added_in_z_config_1_19_with_disturbance.py closed_loop_simulation_cluster_with_noise_added_in_z_config_1_20_with_disturbance.py ;
# \
#           closed_loop_simulation_cluster_with_noise_added_4.py closed_loop_simulation_cluster_with_noise_added_5.py \
#           closed_loop_simulation_cluster_with_noise_added_6.py ;
do
  sbatch -J "${s%.py}" -p cpu -t 15:00:00 -c 1 --mem=6G -o sim_logs/%x_%j.out \
    --export=ALL \
    --wrap "
    set -euo pipefail;
    module purge; 
    module load devel/python/3.11.7-gnu-14.2; 
    source ../../venv/bin/activate;
    export=ALL,OMP_NUM_THREADS=1,MKL_NUM_THREADS=1,PYTHONUNBUFFERED=1;
    srun -c ${SLURM_CPUS_PER_TASK:-1} python -u $s"
done
